// Industry-specific expense categories
export const INDUSTRY_CATEGORIES: Record<string, string[]> = {
  'Real Estate': [
    'Property Showings',
    'Marketing & Advertising',
    'Office Rent',
    'MLS Fees',
    'Professional Development',
    'Client Meals',
    'Photography',
    'Staging',
    'Legal Fees',
    'Insurance',
  ],
  'Construction & Trades': [
    'Tools & Equipment',
    'Materials & Supplies',
    'Vehicle Maintenance',
    'Fuel',
    'Permits & Licenses',
    'Insurance',
    'Safety Equipment',
    'Subcontractors',
    'Office Supplies',
    'Marketing',
  ],
  'Healthcare & Medical': [
    'Medical Supplies',
    'Equipment',
    'Continuing Education',
    'Professional Licenses',
    'Malpractice Insurance',
    'Office Rent',
    'Lab Fees',
    'Medical Software',
    'Marketing',
    'Staff Uniforms',
  ],
  'Consulting & Professional Services': [
    'Client Meetings',
    'Travel & Lodging',
    'Software Subscriptions',
    'Office Supplies',
    'Professional Development',
    'Marketing',
    'Insurance',
    'Coworking Space',
    'Conference Fees',
    'Legal & Accounting',
  ],
  'Retail & E-commerce': [
    'Inventory',
    'Packaging & Shipping',
    'Point of Sale System',
    'Rent & Utilities',
    'Marketing & Ads',
    'Website Hosting',
    'Payment Processing Fees',
    'Insurance',
    'Store Fixtures',
    'Photography',
  ],
  'Restaurant & Food Service': [
    'Food & Ingredients',
    'Kitchen Equipment',
    'Staff Uniforms',
    'Rent & Utilities',
    'Licenses & Permits',
    'Marketing',
    'POS System',
    'Cleaning Supplies',
    'Insurance',
    'Waste Disposal',
  ],
  'Technology & Software': [
    'Software Licenses',
    'Cloud Services',
    'Development Tools',
    'Hardware',
    'Internet & Hosting',
    'Marketing',
    'Contract Labor',
    'Professional Development',
    'Office Equipment',
    'Insurance',
  ],
  'Transportation & Delivery': [
    'Fuel',
    'Vehicle Maintenance',
    'Vehicle Insurance',
    'Tolls & Parking',
    'GPS & Navigation',
    'Vehicle Lease',
    'Licenses & Permits',
    'Safety Equipment',
    'Phone & Data',
    'Marketing',
  ],
  'Creative Services': [
    'Software Subscriptions',
    'Stock Photos/Assets',
    'Equipment',
    'Portfolio Website',
    'Marketing',
    'Coworking Space',
    'Client Meetings',
    'Professional Development',
    'Insurance',
    'Supplies',
  ],
  'Legal Services': [
    'Legal Research',
    'Bar Dues',
    'Continuing Legal Education',
    'Malpractice Insurance',
    'Office Rent',
    'Legal Software',
    'Marketing',
    'Client Entertainment',
    'Filing Fees',
    'Professional Memberships',
  ],
  'Accounting & Bookkeeping': [
    'Accounting Software',
    'Professional Licenses',
    'Continuing Education',
    'Insurance',
    'Office Rent',
    'Marketing',
    'Client Meetings',
    'Professional Memberships',
    'Office Supplies',
    'Tax Research',
  ],
  'Fitness & Wellness': [
    'Equipment',
    'Rent & Utilities',
    'Insurance',
    'Certifications',
    'Marketing',
    'Music Licensing',
    'Cleaning Supplies',
    'Retail Products',
    'Website & Apps',
    'Uniforms',
  ],
  'Photography & Videography': [
    'Camera Equipment',
    'Lighting & Gear',
    'Editing Software',
    'Storage & Backup',
    'Marketing',
    'Travel',
    'Insurance',
    'Website Hosting',
    'Props & Backdrops',
    'Education',
  ],
  'Other': [
    'General Business Expenses',
    'Office Supplies',
    'Marketing',
    'Insurance',
    'Professional Development',
    'Travel',
    'Meals & Entertainment',
    'Utilities',
    'Equipment',
    'Software',
  ],
};

export const INDUSTRIES = Object.keys(INDUSTRY_CATEGORIES).sort();

export function getIndustryCategories(industry: string): string[] {
  return INDUSTRY_CATEGORIES[industry] || [];
}

export function getAllIndustries(): string[] {
  return INDUSTRIES;
}
